apiVersion: v1
kind: LimitRange
metadata:
  name: devops-limitrange
  namespace: devops
spec:
  limits:
  - default:
      cpu: "800m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "128Mi"
    type: Container
