apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc
    annotations:
      description: "this is demo"
spec:
   replicas: 3
   selector:
      app: myapp
   template:
      metadata: 
        labels:
           app: myapp
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80


