apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myrs
    annotations:
      description: "this is demo"
spec:
   replicas: 4
   selector:
      matchExpressions:
       - key: app
         operator: In
         values: [myapp]
       - key: env
         operator: NotIn
         values: [dev]
   template:
      metadata: 
        labels:
           app: myapp
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
     app: myapp
   ports:
   - port: 80
     nodePort: 30123

