apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
   replicas: 1
   selector:
     matchLabels:
      app: mywp
   template:
      metadata: 
        labels:
           app: mywp
      spec:
        volumes: 
        - name: myvol
          configMap:
             name: myindex
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /usr/share/nginx/html

           

---
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
     app: mywp
   ports:
   - port: 80
     nodePort: 30123
---
apiVersion: v1
data:
  index.html: |
    <h1> Hello From ConfigMap... </h1>
kind: ConfigMap
metadata:
  name: myindex
