apiVersion: apps/v1
kind: Deployment
metadata:
    name: sec-test
spec:
   replicas: 1
   selector:
     matchLabels:
      app: mywp
   template:
      metadata: 
        labels:
           app: mywp
      spec:
        volumes: 
        - name: myvol
          secret:
             secretName: pfile
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /usr/share/nginx/html

           

---
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
     app: mywp
   ports:
   - port: 80
     nodePort: 30123
---
apiVersion: v1
data:
  pass.txt: dGVzdDEyMw==
kind: Secret
metadata:
  name: pfile
