apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
   replicas: 1
   selector:
     matchLabels:
      app: mywp
   template:
      metadata: 
        labels:
           app: mywp
      spec:
        containers:
        - name: con1
          image: wordpress:latest
          ports:
          - containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            value: mydb-svc
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
                secretKeyRef: 
                   name: pass
                   key: PASS 
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_TABLE_PREFIX
            value: wp_

---
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
     app: mywp
   ports:
   - port: 80
     nodePort: 30123
---
apiVersion: v1
data:
  WORDPRESS_DB_HOST: mydb-svc
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: test123
  WORDPRESS_DB_USER: root
  WORDPRESS_TABLE_PREFIX: wp_
kind: ConfigMap
metadata:
  name: myenv
