apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30123
  selector:
    run: mypod
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /data
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc
